# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32stdc++6

# Set the build environment
env:
    - SMVERSION=1.8 # Stable
    - SMVERSION=1.9 # Unstable

# Allow the experimental branch to fail
matrix:
  fast_finish: true
  allow_failures:
    - env: SMVERSION=1.9

install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
    - wget https://raw.githubusercontent.com/psychonic/SMRCon/master/sourcemod/scripting/include/smrcon.inc -O ./addons/sourcemod/scripting/include/smrcon.inc
before_script:
    - cp -r ./scripting ./addons/sourcemod
    - chmod +x ./addons/sourcemod/scripting/spcomp
    - mkdir ./plugins
# And compile!
script: 
    - ./addons/sourcemod/scripting/spcomp ./addons/sourcemod/scripting/rcon_whitelist.sp -o./plugins/rcon_whitelist_manager.smx
    - ./addons/sourcemod/scripting/spcomp ./addons/sourcemod/scripting/rcon_whitelist_manager.sp -o./plugins/rcon_whitelist_manager.smx

#before_deploy: zip -r rcon_whitelist.zip ./translations/ ./plugins/ ./scripting/ ./data/

#deploy:
#    provider: releases
#    api_key:
#        secure: # To be filled with api_key
#    file: "rcon_whitelist.zip"
#    skip_cleanup: true
#    on:
#        repo: fakuivan/RCON-Whitelist
#        tags: true

# Notifications
notifications:
    email: false
